# Makefile for Pylos.

#=============================================================================#

# Relative path to the directory containing the source code:
SRCDIR := src
# Relative path to the directory that will contain intermediate output files:
OUTDIR := out
# Relative path to the directory that will contain compiled executables:
BINDIR := bin
# Relative path to the directory that will contain documentation:
DOCDIR := doc
# Relative path to the Mac OS X application bundle:
APP_BUNDLE := Pylos.app

# Name of the main executable:
MAIN_EXE := pylos
# Name of the main executable:
TEST_EXE := pylos_test
# The title to use for the documentation:
DOC_TITLE := 'Pylos'

# Flags we want to pass to all invokations of GHC:
GHC_FLAGS := -hidir $(OUTDIR) -odir $(OUTDIR) -stubdir $(OUTDIR) \
	     -i$(SRCDIR) -i$(OUTDIR) -Wall
# For release, add: -O2 -Werror

# List of files to be generated by hsc2hs:
HSC_TARGETS := $(OUTDIR)/Graphics/UI/SDL/Extras.hs \
               $(OUTDIR)/System/MacOSX/Bundle.hs

#=============================================================================#

.PHONY: main
main: $(HSC_TARGETS)
	mkdir -p $(OUTDIR)
	ghc $(GHC_FLAGS) -no-hs-main --make HSMain src/c_main.c \
	    -o $(APP_BUNDLE)/Contents/MacOS/$(MAIN_EXE)

.PHONY: tests
tests:
	mkdir -p $(OUTDIR) $(BINDIR)
	ghc $(GHC_FLAGS) -main-is Test --make Test -o $(BINDIR)/$(TEST_EXE)

$(HSC_TARGETS): $(OUTDIR)/%.hs: $(SRCDIR)/%.hsc
	mkdir -p `dirname $@`
	hsc2hs -o $@ $<

#=============================================================================#

.PHONY: run
run: main
	$(APP_BUNDLE)/Contents/MacOS/$(MAIN_EXE)

.PHONY: test
test: tests
	$(BINDIR)/$(TEST_EXE)

.PHONY: docs
docs: $(OUTDIR)/Graphics/UI/SDL/Extras.hs
	mkdir -p $(DOCDIR)
	find $(SRCDIR) $(OUTDIR) -name '*.hs' -print0 | \
	    xargs -0 haddock --html --odir=$(DOCDIR) --title=$(DOC_TITLE)
	open $(DOCDIR)/index.html

.PHONY: clean
clean:
	rm -rf $(OUTDIR) $(BINDIR) $(DOCDIR)
	rm -f $(APP_BUNDLE)/Contents/MacOS/$(MAIN_EXE)

.PHONY: tidy
tidy:
	find $(SRCDIR) -name '*~' -print0 | xargs -0 rm
	find pov -name '*~' -print0 | xargs -0 rm

.PHONY: wc
wc:
	find $(SRCDIR) \( -name '*.hs' -or -name '*.hsc' \) -print0 | \
	    xargs -0 wc -l

.PHONY: fixme
fixme:
	ack "FIXME|TODO" $(SRCDIR)

#=============================================================================#
